### ISSUE TITLE
I have something for you.

### ISSUE THREAD

**Issue by deavmi** [adulau/Forban#29]
Apparently this software uses `wget`. How about you add `--continue` to the wget command spo that partially downlaoded files can resume from where they stopped if for some reason the have stopped.

**Comment by deavmi** [comment]
Sorry nevermind.

**Comment by adulau** [comment]
If you mean HTTP resume, this can be added. As you need to specify the HTTP Range header in order to download the specific part, the HTTP server should support it. This needs to be checked for CherryPy.

**Comment by deavmi** [comment]
Could you possibly add that feature? @adulau
